version: '3.8'

services:
  strapi:
    image: strapi/strapi:latest
    container_name: strapi
    environment:
      - DATABASE_CLIENT=mysql
      - DATABASE_NAME=strapi
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=rootpassword
    volumes:
      - ./data:/srv/app
    ports:
      - "1337:1337"
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=strapi
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
